/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.smartcred.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author AndreLGSilva
 */
public class TPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TPrincipal
     */
    public TPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesktop = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        mCad = new javax.swing.JMenu();
        mCadClientes = new javax.swing.JMenuItem();
        mCadContrato = new javax.swing.JMenuItem();
        mCadBanco = new javax.swing.JMenuItem();
        mCadPromotora = new javax.swing.JMenuItem();
        mCadGastos = new javax.swing.JMenuItem();
        mCadUsuarios = new javax.swing.JMenuItem();
        mProd = new javax.swing.JMenu();
        mRel = new javax.swing.JMenu();
        mRelProducao = new javax.swing.JMenuItem();
        mRelGastos = new javax.swing.JMenuItem();
        mSobre = new javax.swing.JMenu();
        mSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmPrincipal"); // NOI18N

        javax.swing.GroupLayout pnlDesktopLayout = new javax.swing.GroupLayout(pnlDesktop);
        pnlDesktop.setLayout(pnlDesktopLayout);
        pnlDesktopLayout.setHorizontalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        pnlDesktopLayout.setVerticalGroup(
            pnlDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        mCad.setLabel("Cadastro");

        mCadClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mCadClientes.setText("Clientes");
        mCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadClientesActionPerformed(evt);
            }
        });
        mCad.add(mCadClientes);

        mCadContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mCadContrato.setText("Contrato");
        mCad.add(mCadContrato);

        mCadBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mCadBanco.setText("Banco");
        mCad.add(mCadBanco);

        mCadPromotora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mCadPromotora.setText("Promotora");
        mCad.add(mCadPromotora);

        mCadGastos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mCadGastos.setText("Gastos");
        mCad.add(mCadGastos);

        mCadUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mCadUsuarios.setText("Usuários");
        mCad.add(mCadUsuarios);

        MenuBar.add(mCad);

        mProd.setText("Produção");
        MenuBar.add(mProd);

        mRel.setText("Relatórios");

        mRelProducao.setText("Produção");
        mRel.add(mRelProducao);

        mRelGastos.setText("Gastos");
        mRel.add(mRelGastos);

        MenuBar.add(mRel);

        mSobre.setText("Sobre");
        MenuBar.add(mSobre);

        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        MenuBar.add(mSair);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(pnlDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(736, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadClientesActionPerformed
        // Chamando tela de cadastro de clientes
        //TCadClientes cliente = new TCadClientes();
        //cliente.setVisible(true);
       // pnlDesktop.add(cliente);
    }//GEN-LAST:event_mCadClientesActionPerformed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        // Código para encerrar aplicação:
        int sair = JOptionPane.showConfirmDialog(null, "Deseja realmente fechar o Sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu mCad;
    private javax.swing.JMenuItem mCadBanco;
    private javax.swing.JMenuItem mCadClientes;
    private javax.swing.JMenuItem mCadContrato;
    private javax.swing.JMenuItem mCadGastos;
    private javax.swing.JMenuItem mCadPromotora;
    private javax.swing.JMenuItem mCadUsuarios;
    private javax.swing.JMenu mProd;
    private javax.swing.JMenu mRel;
    private javax.swing.JMenuItem mRelGastos;
    private javax.swing.JMenuItem mRelProducao;
    private javax.swing.JMenu mSair;
    private javax.swing.JMenu mSobre;
    private javax.swing.JPanel pnlDesktop;
    // End of variables declaration//GEN-END:variables
}
